### ISSUE TITLE
Duplicate string in project

### ISSUE THREAD

**Issue by Peurpeule** [Peurpeule/iesa-2019-b3-mobile#1]
Would be better to create a service for tabs button and tab pages name.

**Comment by seiza** [comment]
ca correspond auquel des 3 issues ?

**Comment by Peurpeule** [comment]
Il s'agit simplement de la dernière issue (Point 5) puisque j'avais résolu les points 3 et 4 avant que l'on se mette à créer des issues.
BTW l'issue est résolue

**Comment by seiza** [comment]
ok, créer les 2 autres alors et peut etre renommer celle ci.
